### ISSUE TITLE
about code release

### ISSUE THREAD

**Issue by bxwldljh** [SCZwangxiao/RTQ-MM2023#1]
Hi, nice works! I have noticed that your work is the state-of-the-art result on NeXT QA dataset and I am very interested in it. Can you release your code? Many thanks to you!

**Comment by SCZwangxiao** [comment]
I think the code can be released this month. 

Because MM23 did not send an official paper decision e-mail, the code open-source reviewing process did not begin until the proceedings were released. I am also quite anxious about this since the code release has been delayed for so long.

**Comment by bxwldljh** [comment]
You are very nice! Thanks again!

**Comment by bxwldljh** [comment]
hi, mm23 is over, can you release the code if you have time?

**Comment by SCZwangxiao** [comment]
> hi, mm23 is over, can you release the code if you have time?

Very soon. We've passed the reviewing process, and are working on the codes.

**Comment by bxwldljh** [comment]
Many thanks to you!!!

**Comment by SCZwangxiao** [comment]
> Many thanks to you!!!

Code has been release !!!
