### ISSUE TITLE
yaml参数 model.num_frames和run.evaluate疑问

### ISSUE THREAD

**Issue by dongfengxijian** [SCZwangxiao/RTQ-MM2023#3]
感谢作者分享代码，方便我们学习。我想请问一下yaml文件中model.run_frames参数是指一个视频中提取得帧数吗？此外，run.evaluate参数是干什么用的，我dist_train.sh和dist_test.sh运行时候都是False。

**Comment by SCZwangxiao** [comment]
- 关于 `model.num_frames`
对的。
- 关于 `run. evaluate`
是继承LAVIS时的遗留代码，都设置为False就行。训练和测试通过`dist_train.sh`和`dist_test.sh`完成。
如果设置为`False`，会跳过训练直接进入测试阶段。

**Comment by dongfengxijian** [comment]
@SCZwangxiao 谢谢大佬解释，我明白了。yaml的model.vit_grad_ckpt和model.vit_ckpt_layer两个参数我也不是很明白，这是干什么用的？

**Comment by SCZwangxiao** [comment]
> @SCZwangxiao 谢谢大佬解释，我明白了。yaml的model.vit_grad_ckpt和model.vit_ckpt_layer两个参数我也不是很明白，这是干什么用的？

决定如何使用gradient checkpointing的参数（精度不变、牺牲一些速度换取显存）。
`vit_grad_ckpt `: 是否开启gradient checkpointing。
`vit_ckpt_layer`：从哪一层开始开启gradient checkpointing。

**Comment by dongfengxijian** [comment]
@SCZwangxiao 谢谢大佬指导！
