### ISSUE TITLE
关于evaluation的问题

### ISSUE THREAD

**Issue by dongfengxijian** [SCZwangxiao/RTQ-MM2023#4]
我通过train.sh使用4张卡训练了一个在nextqa测试集上精度为63.22的model，但是当我使用evluation中的相关命令用3张卡重新在nextqa测试集上评估训练好的模型但是显示精度为18.60。

evaluation命令如下：
`bash run_scripts/dist_test.sh configs/rtq/nextqa/rtq_vitb16_f16to4_lr1e-5_8*b16_e6_amp.yaml 3 --options model.load_finetuned="output/nextqa/rtq_vitb16_f16to4_lr1e-5_8*b16_e6_amp/20231208_221701/checkpoint_best.pth" run.batch_size_eval=32`

结果如下：
![34f6a9f4450393c5579fdedd036fc6a](https://github.com/SCZwangxiao/RTQ-MM2023/assets/24863806/36850337-5db8-48b6-bc78-79006e7501d1)

我不太清楚是什么原因导致的。 所以求助一下！

**Comment by SCZwangxiao** [comment]
> 我通过train.sh使用4张卡训练了一个在nextqa测试集上精度为63.22的model，但是当我使用evluation中的相关命令用3张卡重新在nextqa测试集上评估训练好的模型但是显示精度为18.60。
> 
> evaluation命令如下： `bash run_scripts/dist_test.sh configs/rtq/nextqa/rtq_vitb16_f16to4_lr1e-5_8*b16_e6_amp.yaml 3 --options model.load_finetuned="output/nextqa/rtq_vitb16_f16to4_lr1e-5_8*b16_e6_amp/20231208_221701/checkpoint_best.pth" run.batch_size_eval=32`
> 
> 结果如下： ![34f6a9f4450393c5579fdedd036fc6a](https://private-user-images.githubusercontent.com/24863806/291307875-36850337-5db8-48b6-bc78-79006e7501d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNDcyNDksIm5iZiI6MTcwMzA0Njk0OSwicGF0aCI6Ii8yNDg2MzgwNi8yOTEzMDc4NzUtMzY4NTAzMzctNWRiOC00OGI2LWJjNzgtNzkwMDZlNzUwMWQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDA0MzU0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwMWRlZDM1YzE0NmViYmNkZWE1MWNlMmYxODQxMTNjZTNmOTZlY2FhMGQ4ZWQ4N2Q0ODdiMGYxNWFkMTc4OTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zbTBvr6Ekc7itYYdMnD5g8XZkkymE-GxuqA4DqXtBkY)
> 
> 我不太清楚是什么原因导致的。 所以求助一下！

很奇怪。代码应该没有改动吧？然后数据这块是按照`tools/data/nextqa`里面的步骤来的吗？

**Comment by dongfengxijian** [comment]
> > 我通过train.sh使用4张卡训练了一个在nextqa测试集上精度为63.22的model，但是当我使用evluation中的相关命令用3张卡重新在nextqa测试集上评估训练好的模型但是显示精度为18.60。
> > evaluation命令如下： `bash run_scripts/dist_test.sh configs/rtq/nextqa/rtq_vitb16_f16to4_lr1e-5_8*b16_e6_amp.yaml 3 --options model.load_finetuned="output/nextqa/rtq_vitb16_f16to4_lr1e-5_8*b16_e6_amp/20231208_221701/checkpoint_best.pth" run.batch_size_eval=32`
> > 结果如下： ![34f6a9f4450393c5579fdedd036fc6a](https://private-user-images.githubusercontent.com/24863806/291307875-36850337-5db8-48b6-bc78-79006e7501d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNDcyNDksIm5iZiI6MTcwMzA0Njk0OSwicGF0aCI6Ii8yNDg2MzgwNi8yOTEzMDc4NzUtMzY4NTAzMzctNWRiOC00OGI2LWJjNzgtNzkwMDZlNzUwMWQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDA0MzU0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwMWRlZDM1YzE0NmViYmNkZWE1MWNlMmYxODQxMTNjZTNmOTZlY2FhMGQ4ZWQ4N2Q0ODdiMGYxNWFkMTc4OTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zbTBvr6Ekc7itYYdMnD5g8XZkkymE-GxuqA4DqXtBkY)
> > 我不太清楚是什么原因导致的。 所以求助一下！
> 
> 很奇怪。代码应该没有改动吧？然后数据这块是按照`tools/data/nextqa`里面的步骤来的吗？

代码没有改动。数据也是按照tools/data/nextqa里面的步骤来处理的。并且训练过程中的测试结果是正常的。训练过程中的结果如下图：
![image](https://github.com/SCZwangxiao/RTQ-MM2023/assets/24863806/fa3b172e-1eb3-4a86-a098-e0521c56a5a1)
但是不清楚为什么使用dist_test.sh的时候出现这种情况。

**Comment by SCZwangxiao** [comment]
> 我通过train.sh使用4张卡训练了一个在nextqa测试集上精度为63.22的model，但是当我使用evluation中的相关命令用3张卡重新在nextqa测试集上评估训练好的模型但是显示精度为18.60。
> 
> evaluation命令如下： `bash run_scripts/dist_test.sh configs/rtq/nextqa/rtq_vitb16_f16to4_lr1e-5_8*b16_e6_amp.yaml 3 --options model.load_finetuned="output/nextqa/rtq_vitb16_f16to4_lr1e-5_8*b16_e6_amp/20231208_221701/checkpoint_best.pth" run.batch_size_eval=32`
> 
> 结果如下： ![34f6a9f4450393c5579fdedd036fc6a](https://private-user-images.githubusercontent.com/24863806/291307875-36850337-5db8-48b6-bc78-79006e7501d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNzUxODMsIm5iZiI6MTcwMzA3NDg4MywicGF0aCI6Ii8yNDg2MzgwNi8yOTEzMDc4NzUtMzY4NTAzMzctNWRiOC00OGI2LWJjNzgtNzkwMDZlNzUwMWQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDEyMjEyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzMmYyNzZkMjFmMTZjZGVlM2NlZTkwNWE5MmRkZGNiMzc3ZjE5M2JiNjI3NWY3NzJmNjkxZjk3ZjY2MTBiMWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.C8AKDr-3TFOoJIIqB9vh1futcrAzed71sbgEHqS7epg)
> 
> 我不太清楚是什么原因导致的。 所以求助一下！

找到原因了，是因为训练ckpt没有加载。最新的commit https://github.com/SCZwangxiao/RTQ-MM2023/commit/4de0c3e9abe05d118bcb562023ac88f7b5391fb1 已经修复了这个问题。

你看看是否能够正常inference？

具体来说又是来自LAVIS的遗留问题：
（1）参数错误：`model.load_finetuned: bool`只决定是否load预训练参数，`model.finetuned: str`才用来指定ckpt地址。
（2）MC_QA模型参数加载问题。

**Comment by dongfengxijian** [comment]
> > 我通过train.sh使用4张卡训练了一个在nextqa测试集上精度为63.22的model，但是当我使用evluation中的相关命令用3张卡重新在nextqa测试集上评估训练好的模型但是显示精度为18.60。
> > evaluation命令如下： `bash run_scripts/dist_test.sh configs/rtq/nextqa/rtq_vitb16_f16to4_lr1e-5_8*b16_e6_amp.yaml 3 --options model.load_finetuned="output/nextqa/rtq_vitb16_f16to4_lr1e-5_8*b16_e6_amp/20231208_221701/checkpoint_best.pth" run.batch_size_eval=32`
> > 结果如下： ![34f6a9f4450393c5579fdedd036fc6a](https://private-user-images.githubusercontent.com/24863806/291307875-36850337-5db8-48b6-bc78-79006e7501d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNzUxODMsIm5iZiI6MTcwMzA3NDg4MywicGF0aCI6Ii8yNDg2MzgwNi8yOTEzMDc4NzUtMzY4NTAzMzctNWRiOC00OGI2LWJjNzgtNzkwMDZlNzUwMWQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDEyMjEyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzMmYyNzZkMjFmMTZjZGVlM2NlZTkwNWE5MmRkZGNiMzc3ZjE5M2JiNjI3NWY3NzJmNjkxZjk3ZjY2MTBiMWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.C8AKDr-3TFOoJIIqB9vh1futcrAzed71sbgEHqS7epg)
> > 我不太清楚是什么原因导致的。 所以求助一下！
> 
> 找到原因了，是因为训练ckpt没有加载。最新的commit [4de0c3e](https://github.com/SCZwangxiao/RTQ-MM2023/commit/4de0c3e9abe05d118bcb562023ac88f7b5391fb1) 已经修复了这个问题。
> 
> 你看看是否能够正常inference？
> 
> 具体来说又是来自LAVIS的遗留问题： （1）参数错误：`model.load_finetuned: bool`只决定是否load预训练参数，`model.finetuned: str`才用来指定ckpt地址。 （2）MC_QA模型参数加载问题。

谢谢大佬指点！
